language: node_js
cache: yarn
node_js:
  - '7'
before_script:
  - lerna bootstrap
script:
  - yarn run lint
  - yarn run build
  - yarn run test
# after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
