language: node_js
cache: yarn
node_js:
  - '7'
before_script:
  - yarn run bootstrap
script:
  - yarn run check
  - yarn run build
# after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
