language: node_js
node_js:
  - '4.4'
before_install:
  - npm install -g babel-cli
script:
  - npm run lint
  - npm run build
  - npm run test:cover
  # - npm run test-sauce
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
